server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://111.231.20.113:3306/TradingDB
    username: ms
    password: Trading@sys_9174
    driver-class-name: org.gjt.mm.mysql.Driver
  application:
    name: orderService
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848 # nacos 服务端地址


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-handlers-package: org.wallstreetWolf.common.typeHandler
  type-aliases-package: org.wallstreetWolf.common.pojo    # 所有pojo别名类所在包
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: true
    db-config:
      id-type: assign_id
      update-strategy: not_null
  extension:
    enabled: true
    mapper-package: org.wallstreetWolf.common.mapper
    data-permission:
      enabled: true
